services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: aiosghjdaogyiphdioUAHSDIUhasiud1erASD2q231d
      POSTGRES_DB: prod
    ports:
      - '7432:5432'